name: Build LLVM nightly

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

# Cancel the workflow if a new one is requested for the same PR/branch, but still test all commits on the master branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master'}}

jobs:

  CI-LLVM-nightly:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:rolling

    steps:
      - run: apt-get update
      - run: apt-get -qq install -y gcc g++ wget lsb-release wget software-properties-common gnupg git cmake flex python3-pebble python3-psutil python3-chardet python3-msgspec python3-pytest python3-pytest-mock python3-pytest-subprocess python3-pytest-xdist python3-jsonschema python3-zstandard vim unifdef sudo
      - uses: rui314/setup-mold@v1
      - run: ld --version
      - run: nproc
      - run: wget https://apt.llvm.org/llvm.sh
      - run: chmod +x llvm.sh
      - run: ./llvm.sh 21
      - run: apt-get install -y bolt-21 clang-21 libclang-common-21-dev libclang-21-dev mlir-21-tools llvm-21-tools libclang-common-21-dev libclang-21-dev libclang1-21 clang-format-21 python3-clang-21 clangd-21 clang-tidy-21 libomp-21-dev
      # TODO: remove in the future
      - run: touch /usr/lib/llvm-21/lib/libLibcTableGenUtil.a
      - uses: actions/checkout@v4
      - run: mkdir objdir
      - run: cmake ..
        working-directory: objdir
      - run: make -j $(($(nproc) + 1)) VERBOSE=1
        working-directory: objdir
      - run: pytest -n $(($(nproc) + 1))
        working-directory: objdir
